[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
palm_presale = "Duom8WAbX4qfnS5UNkvEiPeA2KzFhk7dShVcRom8dHPj"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/root/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
